repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-json
  - id: name-tests-test
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
- hooks:
  - id: commitizen
#  - id: commitizen-branch
    stages:
#    - push
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
